<a href="https://colab.research.google.com/github/MikeRodziewicz/Udemy_ML_Bootcamp/blob/main/data_science_part_one.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
np.__version__

'1.21.5'

In [25]:
z = np.array(
    [[[1,2,3],
      [3,4,5]],

    [[4,5,6],
     [1,2,3]]]

)
z

array([[[1, 2, 3],
        [3, 4, 5]],

       [[4, 5, 6],
        [1, 2, 3]]])

In [27]:
z.shape

(2, 2, 3)

In [32]:
np.full(shape=(3,4), fill_value=4)

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.linspace(start=0, stop=1, num=4)

array([0, 0, 0, 1])

In [5]:
a = np.arange(15)

In [ ]:
a.reshape(3,5)

In [7]:
A = np.array([3,1,4,2])
B = np.array([3,-1,3,2])

In [8]:
A + B

array([6, 0, 7, 4])

In [10]:
X = np.array([[1,3], [-2,0]])
Y = np.array([[6,0], [-1,2]])
print(X)
print(Y)

[[ 1  3]
 [-2  0]]
[[ 6  0]
 [-1  2]]


In [11]:
X * Y

array([[6, 0],
       [2, 0]])

In [12]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [13]:
C = np.random.rand(5)

In [14]:
C

array([0.74126564, 0.88465896, 0.91882446, 0.85875325, 0.71143879])

In [16]:
C[np.argmax(C)]

0.9188244555096765

In [17]:
D = np.arange(20)
D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [18]:
D = D.reshape(4,5)
D

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [19]:
D[:,2]

array([ 2,  7, 12, 17])