<a href="https://colab.research.google.com/github/MikeRodziewicz/Udemy_ML_Bootcamp/blob/main/data_science_part_one.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'1.21.5'

In [ ]:
z = np.array(
    [[[1,2,3],
      [3,4,5]],

    [[4,5,6],
     [1,2,3]]]

)
z

array([[[1, 2, 3],
        [3, 4, 5]],

       [[4, 5, 6],
        [1, 2, 3]]])

In [ ]:
z.shape

(2, 2, 3)

In [ ]:
np.full(shape=(3,4), fill_value=4)

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(start=0, stop=1, num=4)

array([0, 0, 0, 1])

In [ ]:
a = np.arange(15)

In [ ]:
a.reshape(3,5)

In [ ]:
A = np.array([3,1,4,2])
B = np.array([3,-1,3,2])

In [ ]:
A + B

array([6, 0, 7, 4])

In [ ]:
X = np.array([[1,3], [-2,0]])
Y = np.array([[6,0], [-1,2]])
print(X)
print(Y)

[[ 1  3]
 [-2  0]]
[[ 6  0]
 [-1  2]]


In [ ]:
X * Y

array([[6, 0],
       [2, 0]])

In [ ]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
C = np.random.rand(5)

In [ ]:
C

array([0.74126564, 0.88465896, 0.91882446, 0.85875325, 0.71143879])

In [ ]:
C[np.argmax(C)]

0.9188244555096765

In [ ]:
D = np.arange(20)
D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
D = D.reshape(4,5)
D

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
D[:,2]

array([ 2,  7, 12, 17])

In [6]:
v1 = np.array([-1,4])
v1

array([-1,  4])

In [7]:
np.linalg.norm(v1)

4.123105625617661

In [4]:
v2 = np.array([-10,10,13])

In [5]:
np.linalg.norm(v2)

19.209372712298546

In [11]:
price = np.array([[12.40, 12.80, 11.90, 1000],
                 [12.50, 14.80, 13.90, 1200],
                 [12.90, 10.80, 16.90, 1300]])
print(price)

[[  12.4   12.8   11.9 1000. ]
 [  12.5   14.8   13.9 1200. ]
 [  12.9   10.8   16.9 1300. ]]


In [13]:
price.sum(axis=0)

array([  37.8,   38.4,   42.7, 3500. ])

In [14]:
price.sum(axis=1)

array([1037.1, 1241.2, 1340.6])

In [15]:
np.min(price, axis=0)

array([  12.4,   10.8,   11.9, 1000. ])